apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.oracle.name }}
  namespace: {{ .Values.oracle.namespace }}
  labels:
    group: {{ .Values.oracle.group }}
spec:
  type: {{ .Values.oracle.service.type }}
  selector:
    app: {{ .Values.oracle.name }}
  ports:
    - port: {{ .Values.oracle.service.port }}
      targetPort: {{ .Values.oracle.container.port }}
