server:
  port: 9002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    registryFetchIntervalSeconds: 5

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000