version: '3'
services:
  active-mq:
    image: webcenter/activemq:5.14.3
    container_name: active-mq
    networks:
      - backend
    ports:
      # mqtt
      - "1883:1883"
      # amqp
      - "5672:5672"
      # ui
      - "8161:8161"
      # stomp
      - "61613:61613"
      # ws
      - "61614:61614"
      # jms
      - "61616:61616"
    volumes:
      - "activemq-conf:/opt/activemq/conf"
      - "activemq-data:/data/activemq"
      - "activemq-log:/var/log/activemq"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_WRITE_LOGIN: write
      ACTIVEMQ_WRITE_PASSWORD: write
      ACTIVEMQ_READ_LOGIN: read
      ACTIVEMQ_READ_PASSWORD: read
      ACTIVEMQ_JMX_LOGIN: jmx
      ACTIVEMQ_JMX_PASSWORD: password
      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 256
      ACTIVEMQ_MAX_MEMORY: 512
networks:
  backend:
      driver: bridge
volumes:
  activemq-conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/docker/setup/activemq/conf
  activemq-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/docker/setup/activemq/data
  activemq-log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/docker/setup/activemq/log