version: '3'
services:
  discovery-server:
    container_name: discovery-server
    build: ./discovery-server
    networks:
      - backend
    environment:
      - "JAVA_OPTS=-Xms16m -Xmx128m -Xmn64m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "8761:8761"
    volumes:
      - "logs:/opt/app/logs"
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms16m -Xmx128m -Xmn64m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "2407:2407"
    volumes:
      - "logs:/opt/app/api-gateway/logs"
  authorization-service:
    container_name: authorization-service
    build: ./authorization-service
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms16m -Xmx128m -Xmn64m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "9001:9001"
    volumes:
      - "logs:/opt/app/logs"
    extra_hosts:
      - "vnmch-db-01:10.60.157.12"
  common-service:
    container_name: common-service
    build: ./common-service
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms16m -Xmx128m -Xmn64m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "9002:9002"
    volumes:
      - "logs:/opt/app/common-service/logs"
    extra_hosts:
      - "vnmch-db-01:10.60.157.12"
  customer-service:
    container_name: customer-service
    build: ./customer-service
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms32m -Xmx256m -Xmn128m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "9003:9003"
    volumes:
      - "logs:/opt/app/customer-service/logs"
    extra_hosts:
      - "vnmch-db-01:10.60.157.12"
  promotion-service:
    container_name: promotion-service
    build: ./promotion-service
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms32m -Xmx256m -Xmn128m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "9004:9004"
    volumes:
      - "logs:/opt/app/promotion-service/logs"
    extra_hosts:
      - "vnmch-db-01:10.60.157.12"
  report-service:
    container_name: report-service
    build: ./report-service
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms32m -Xmx256m -Xmn128m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "9005:9005"
    volumes:
      - "logs:/opt/app/report-service/logs"
    extra_hosts:
      - "vnmch-db-01:10.60.157.12"
  sale-service:
    container_name: sale-service
    build: ./sale-service
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE= local"
      - "JAVA_OPTS=-Xms32m -Xmx256m -Xmn128m"
      - "TZ=Asia/Ho_Chi_Minh"
    ports:
      - "9006:9006"
    volumes:
      - "logs:/opt/app/sale-service/logs"
    extra_hosts:
      - "vnmch-db-01:10.60.157.12"
networks:
  backend:
    driver: bridge
volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:/docker/setup/api/logs
