# Default values for ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
ingress:
  name: vinamilk-ingress-service
  annotations:
    class: nginx
    crt: letsencrypt-prod
  hosts:
    - host: rancher.imt-soft.com
      paths:
        - path: /api
          backend:
            serviceName: api-gateway
            servicePort: 80
        - path: /ui
          backend:
            serviceName: kch-web
            servicePort: 80
        - path: /discovery/
          backend:
            serviceName: discovery-server
            servicePort: 80
  clusterissuer:
    name: letsencrypt-prod
    email: tienld@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    ingressClass: nginx
  cert:
    name: rancher-imt-tls
    secretName: rancher-imt
    hostName: rancher.imt-soft.com
