server:
  port: 2407
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      serviceId: authorization-service
      path: /api/user/**
      strip-prefix: false
      common-service:
        serviceId: common-service
        path: /api/location/**
        strip-prefix: false
      customer-service:
        serviceId: customer-service
        path: /api/customer/**
        strip-prefix: false
      promotion-service:
        serviceId: promotion-service
        path: /api/promotion/**
        strip-prefix: false
      report-service:
        serviceId: report-service
        path: /api/report/**
        strip-prefix: false
      sale-service:
        serviceId: sale-service
        path: /api/sale/**
        strip-prefix: false
      setting-service:
        serviceId: setting-service
        path: /api/setting/**
        strip-prefix: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
