server:
  port: 2408
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      serviceId: authorization-service
      path: /**
      strip-prefix: false
    common-service:
      serviceId: common-service
      path: /api/location/**
    customer-service:
      serviceId: customer-service
      path: /api/customer/**
    promotion-service:
      serviceId: promotion-service
      path: /api/promotion/**
    report-service:
      serviceId: report-service
      path: /api/report/**
    sale-service:
      serviceId: sale-service
      path: /api/sale/**
    setting-service:
      serviceId: setting-service
      path: /api/setting/**

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
            
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
