server:
  port: 2408
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      serviceId: authorization-service
      path: /**
      strip-prefix: false
    salon-service:
      serviceId: salon-service
      path: /api/salon/**
    setting-day-service:
      serviceId: setting-day-service
      path: /api/setting-day/**
    group-service:
      serviceId: group-service
      path: /api/group/**
    payment-service:
      serviceId: payment-service
      path: /api/payment/**
    item-setting-service:
      serviceId: item-setting-service
      path: /api/item-setting/**
    reservation-service:
      serviceId: reservation-service
      path: /api/reservation/**
    company-service:
      serviceId: company-service
      path: /api/company/**
    reception-service:
      serviceId: reception-service
      path: /api/reception/**

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
