server:
  port: 2407
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      serviceId: authorization-service
      path: /api/v1/user/**
      strip-prefix: false
    common-service:
      serviceId: common-service
      path: /api/v1/common/**
      strip-prefix: false
    customer-service:
      serviceId: customer-service
      path: /api/v1/customers/**
      strip-prefix: false
    promotion-service:
      serviceId: promotion-service
      path: /api/v1/promotion/**
      strip-prefix: false
    report-service:
      serviceId: report-service
      path: /api/v1/report/**
      strip-prefix: false
    sale-service:
      serviceId: sale-service
      path: /api/v1/sale/**
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
