server:
  port: 2407
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
#    registryFetchIntervalSeconds: 5
    preferIpAddress: false
  client:
#    fetchRegistry: true
#    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      serviceId: authorization-service
      path: /api/v*/users/**
      strip-prefix: false
    common-service:
      serviceId: common-service
      path: /api/v*/commons/**
      strip-prefix: false
    customer-service:
      serviceId: customer-service
      path: /api/v*/customers/**
      strip-prefix: false
    promotion-service:
      serviceId: promotion-service
      path: /api/v*/promotions/**
      strip-prefix: false
    report-service:
      serviceId: report-service
      path: /api/v*/reports/**
      strip-prefix: false
    sale-service:
      serviceId: sale-service
      path: /api/v*/sales/**
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
