server:
  port: 2407
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      serviceId: authorization-service
      path: /**
      strip-prefix: false
    common-service:
      serviceId: common-service
      path: /api/location/**
    customer-service:
      serviceId: customer-service
      path: /api/customer/**
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
            
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
