server:
  port: 9001
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@vnmch-db-01:1521/db12c
    username: VINAMILKCH_AUTH
    password: VINAMILKCH_AUTH#123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2