server:
<<<<<<< HEAD
<<<<<<< HEAD:customer-service/src/main/resources/application-docker.yml
  port: 9003
=======
  port: 9004
>>>>>>> Changed ORACLE DB and added docker:promotion-service/src/main/resources/application-docker.yml
=======
  port: 9003
>>>>>>> Changed ORACLE DB and added docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000