spring:
  application:
    name: customer-service
  profiles:
    active:
      - dev
  cloud:
    config:
      uri: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: self,health,info,refresh