apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  labels:
    group: {{ .Values.server.group }}
spec:
  type: {{ .Values.server.service.type }}
  selector:
    app: {{ .Values.server.name }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.container.port }}
