server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: null
        native:
          searchLocations: classpath:api-gateway/, classpath:authorization-service/, classpath:discovery-server/, classpath:setting-service/, classpath:common-service/, classpath:customer-service/, classpath:promotion-service/, classpath:report-service/, classpath:sale-service/
spring.profiles.active: native

