server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_services
    username: shoutengai
    password: shoutengai
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/