# Default values for server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
server:
  name: "api-gateway"
  group: "server"
  image:
    tag: latest
    repository: "api-gateway"
    package_location: "192.168.100.118:10001"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  container:
    port: 2407
    config: []
    env:
      - key: SPRING_PROFILES_ACTIVE
        value: ci
      - key: EUREKA_URL
        value: 'http://discovery-server/eureka'
      - key: DB_URL
        value: 'jdbc:oracle:thin:@vnmch-db-01:1521/db12c'

