server:
  port: ${SERVICE_PORT}
eureka:
  instance:
    hostname: ${HOSTNAME}.eureka
  client:
    defaultZone: ${EUREKA_SERVER_ADDRESS}
  server:
    wait-time-in-ms-when-sync-empty: 0
    peer-node-read-timeout-ms: 2000
